### ISSUE TITLE
[PYTHON] Resolve Python issues regarding code completions with continue.dev

### ISSUE THREAD

**Issue by ryanweiler92** [SEMOSS/semoss#750]
### Description 

When attempting to use a model through SEMOSS for code completions with the continue.dev extension in VSCode, we seem to face several issues. Attempt to hook up the extension to our backend and get working code completions from various models. 

### Existing

1. Install the Continue.dev extension for VSCode. 
2. Open the extension and click the dropdown and click the options "+ Add Chat model".
3. On the resulting screen, click on the link at the bottom that says "config file". This will open a YAML file.
4. Add local models to the models block of the YAML file. 
```yaml
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: SEMOSS GPT-4o Local
    provider: openai
    model: 4acbe913-df40-4ac0-b28a-daa5ad91b172
    apiBase: http://localhost:9090/Monolith/api/model/openai
    apiKey: your-local-access-key:your-local-secret-key
    roles:
      - chat
      - edit
      - apply
      - autocomplete
```
NOTE: The reference to your access key and local key refer to your SEMOSS keys that are generated within the UI. 

You can switch which model is used for autocompletes by removing the autocomplete flag from the roles and adding an additional model. 

```yaml
models:
  - name: SEMOSS Llama3-70B-Instruct Local
    provider: openai
    model: 4801422a-5c62-421e-a00c-05c6a9e15de8
    apiBase: http://localhost:9090/Monolith/api/model/openai
    apiKey: your-local-access-key:your-local-secret-key
    roles:
      - autocomplete
```

I would recommend running your model in FORCE PORT mode to debug what is happening. You can do this by adding the line `FORCE_PORT 9999` to the bottom of the SMSS for a given model. Then open the `gaas_tcp_socket_server.py` file in VSCode and run the file in debug mode. This will start a TCP server on port 9999. You can now place breakpoints in the files of the Py directory to debug. 

### Requirements

Working code completions with an OpenAI and Llama model.
